apiVersion: v1
kind: Secret
metadata:
  name: fiap-mp-secret-pagamento
  namespace: fiap-soat11
type: Opaque
data:
  MercadoPago__AccessToken: VEVTVC04NDIwODUzODI0NTAxNzk2LTA1MTYxMy01ZjZmMDE5ZWRiNThjNTQyMzRkZDg5ODQ2MzExZjgwOS0xNTE5NjkyNTY=