apiVersion: v1
kind: Secret
metadata:
  name: fiap-db-secret
  namespace: fiap-soat11
type: Opaque
#data:
stringData:
  #ConnectionStrings__DefaultConnection: U2VydmVyPWZpYXAtbXlzcWwtbXlzcWwuY2JzMmFrbTZlMjA2LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1maWFwO1VzZXIgSUQ9dXNlcl9maWFwO1Bhc3N3b3JkPXBhc3NfZmlhcDsK
  ConnectionStrings__DefaultConnection: Server=__DB_HOST__;Port=3306;Database=fiapx;Uid=user_fiap;Pwd=pass_fiap;