apiVersion: v1
kind: Secret
metadata:
  name: fiap-db-secret-preparo
  namespace: fiap-soat11
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPWZpYXAtbXlzcWwtbXlzcWwuY2JzMmFrbTZlMjA2LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1maWFwO1VzZXIgSUQ9dXNlcl9maWFwO1Bhc3N3b3JkPXBhc3NfZmlhcDsK