apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fiap-soat11
type: Opaque
data:
  # Credentials (base64 encoded)
  # username: admin (YWRtaW4=)
  # password: fiaprabbitmq (ZmlhcHJhYmJpdG1x)
  rabbitmq-username: YWRtaW4=
  rabbitmq-password: ZmlhcHJhYmJpdG1x
