apiVersion: v1
kind: Service
metadata:
  name: fiap-svc-preparo
  namespace: fiap-soat11
spec:
  selector:
    app: fiap-deployment-preparo
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: LoadBalancer