apiVersion: v1
kind: Service
metadata:
  name: fiap-svc-usuario
  namespace: fiap-soat11
spec:
  selector:
    app: fiap-deployment-usuario
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer