apiVersion: v1
kind: Service
metadata:
  name: fiap-svc-pedido
  namespace: fiap-soat11
spec:
  selector:
    app: fiap-deployment-pedido
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer